### ISSUE TITLE
Many language codes are documented but not accepted. 

### ISSUE THREAD

**Issue by jkelly-kantar** [TextRazor/textrazor-python#15]
I came across an apparent bug whereby the majority of language codes documented on https://www.textrazor.com/languages are rejected by the API, with a TextRazorAnalysisException being raised, following an apparent 400 status code.

Of the 143 languages documented on the above-linked page, only 19 appear to be accepted in practice.

The error message looks like
`TextRazor cannot analyze documents of language: cze`

In addition, when language isn't supplied (and autodetection is used), it's possible that one of these documented but rejected languages is selected.
This means the user is told they can't use a language which they never selected.

Please see the Python script in [this zip folder](https://github.com/TextRazor/textrazor-python/files/12660942/test_replicate_lang_issue.zip) for 2 test cases, one to cover the autodetection issue and one to cover the wider issue of language support.

You should be able to run this with standard Python installed + textrazor:

`python test_replicate_lang_issue.py`

I was running the tests with a text file containing my API key called `api_key.txt` stored in the same directory as the python script.

Please could this be looked into?
I'm assuming it's not the Python client itself at fault, but I wasn't sure where else to raise this.
Thanks

**Comment by crayston** [comment]
Hi @jkelly-kantar, 
We currently support the 19 languages listed at the top of https://www.textrazor.com/languages with our full Entity Extraction, Topic Tagging and Classification system. Our language detector is capable of identifying far more than we are capable of analyzing, those are listed further down that page. The error is intentional - if we detect language as one we don't support, typically it's better to halt the process instead of guessing a language. This is useful where you are analyzing eg web content, which may be in any language. Where you know in advance the source language you can set the override to mitigate any potential errors in the language detection logic.

Hope that is clear - if there's anything else feel free to drop an email to support@textrazor.com
Thanks

**Comment by jkelly-kantar** [comment]
> Hi @jkelly-kantar, We currently support the 19 languages listed at the top of https://www.textrazor.com/languages with our full Entity Extraction, Topic Tagging and Classification system. Our language detector is capable of identifying far more than we are capable of analyzing, those are listed further down that page. The error is intentional - if we detect language as one we don't support, typically it's better to halt the process instead of guessing a language. This is useful where you are analyzing eg web content, which may be in any language. Where you know in advance the source language you can set the override to mitigate any potential errors in the language detection logic.
> 
> Hope that is clear - if there's anything else feel free to drop an email to [support@textrazor.com](mailto:support@textrazor.com) Thanks

Thanks @crayston for the clear explanation, that does make sense.
I think we had just misread / misunderstood the docs! :smile:
